### ISSUE TITLE
Less verbose package.json scripts

### ISSUE THREAD

**Issue by hybrist** [todoubled/test-ium#1]
Hi - long time no see! :) Just saw this repo pop up in my stream, hope you don't mind this. Would create a PR but right now a bit in a hurry. `npm` adds `./node_modules/.bin` to the path by default, so it could just be:

``` json
  "scripts": {
    "test": "mocha test/integration.coffee",
    "start": "coffee test/app.coffee"
  }
```

**Comment by todoubled** [comment]
Hey Jan! Thanks for the tip, I appreciate it. :guitar:
